<?php

use App\Plant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(Plant::class, 40)->create();
        DB::table('plants')->insert([
            [
                'title' => 'Strawberry',
                'category' => 'Fruit',
                'image' => 'https://images.unsplash.com/photo-1554118879-e459bb1fe1ca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=655&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1 / week',
                'seedling_light' => 'Full sun',
                'planting_frequency' => '1 / week',
                'planting_sprouting' => '2-3 weeks',
                'description' => 'The strawberry is a red fruit derived from strawberries, a herbaceous plant species belonging to the genus Fragaria (family Rosaceae), of which several varieties are cultivated.',
                'localisation' => '',
            ],
            [
                'title' => 'Raspberry',
                'category' => 'Fruit',
                'image' => 'https://images.unsplash.com/photo-1583513369312-d404cbaac3eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '3 / week',
                'seedling_light' => 'Sun',
                'planting_frequency' => '3 / week',
                'planting_sprouting' => '4 weeks',
                'description' => 'The raspberry is a red fruit from the raspberry tree (Rubus idaeus), a shrub of the rosaceae family. Depending on whether wild or cultivated raspberries are grown, raspberries weigh 4 to 10 g, measure up to 2.5 cm and have 40 to 80 drupeoles',
                'localisation' => '',
            ],
            [
                'title' => 'Apricot',
                'category' => 'Fruit',
                'image' => 'https://images.unsplash.com/photo-1501746877-14782df58970?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1 / week',
                'seedling_light' => 'Sun',
                'planting_frequency' => '3 / week',
                'planting_sprouting' => '1 month',
                'description' => 'The apricot is the fruit of a generally small tree called apricot tree, of the Rosaceae family. The scientific name of the apricot tree is Prunus armeniaca (Armenian plum). It belongs to the subgenus Prunus, section Armeniaca along with the other four apricot trees in the world.',
                'localisation' => '',
            ],
            [
                'title' => 'Kiwi',
                'category' => 'Fruit',
                'image' => 'https://images.unsplash.com/photo-1585059895524-72359e06133a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1 / week',
                'seedling_light' => 'Sun',
                'planting_frequency' => '1 / week',
                'planting_sprouting' => '2 month',
                'description' => 'Kiwis are fruits of several species of lianas of the genus Actinidia, family Actinidiaceae. They originate from China, particularly from the province of Shaanxi. They are also found in so-called tropical mountain climates. In France, Adour kiwis have a PGI and a red label.

Its pulp, which is generally green, sweet and tart, surrounded by a brown, downy (hairy) skin, contains about a hundred tiny edible black seeds. The kiwi is a source of vitamin C, but also of vitamins A and E, calcium, iron and folic acid.',
                'localisation' => '',
            ],
            [
                'title' => 'Apple',
                'category' => 'Fruit',
                'image' => 'https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '2 / week',
                'seedling_light' => 'Sun',
                'planting_frequency' => '3 / week',
                'planting_sprouting' => '2 month',
                'description' => 'The apple is an edible fruit produced by an apple tree. Apple trees are grown worldwide and are the most widely cultivated species of the genus Malus. The tree is native to Central Asia, where its wild ancestor, Malus sieversii, can still be found today. Apples have been cultivated for thousands of years in Asia and Europe and were imported to North America by European settlers. Apples have religious and mythological significance in many cultures, including Norse and Greek mythology and the Christian tradition of Europe.',
                'localisation' => '',
            ],
            [
                'title' => 'Tomato',
                'category' => 'Vegetable',
                'image' => 'https://images.unsplash.com/photo-1576856497337-4f2be24683da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1282&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '5 / week',
                'seedling_light' => 'Sun',
                'planting_frequency' => '5 / week',
                'planting_sprouting' => '2.5 week',
                'description' => 'Tomato (Solanum lycopersicum L.) is a herbaceous plant species of the genus Solanum of the Solanaceae family, native to northwestern South America and widely cultivated for its fruit. The term also refers to the fleshy fruit. The tomato is eaten as a fruiting vegetable, either raw or cooked. It has become an essential part of gastronomy in many countries, especially in the Mediterranean basin.',
                'localisation' => '',
            ],
            [
                'title' => 'French beans',
                'category' => 'Vegetable',
                'image' => 'https://images.unsplash.com/photo-1560252030-9fc63cb78dac?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '3 / week',
                'seedling_light' => 'Windy',
                'planting_frequency' => '3 / week',
                'planting_sprouting' => '1 week',
                'description' => 'Green beans are immature pods of the common bean (Phaseolus vulgaris) eaten as vegetables. Depending on the variety, their colour can vary between yellow ("butter" beans), green and purple.',
                'localisation' => '',
            ],
            [
                'title' => 'Zucchini',
                'category' => 'Vegetable',
                'image' => 'https://images.unsplash.com/photo-1549223672-c262a3763aab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1.5 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '1.5 / week',
                'planting_sprouting' => '2 month',
                'description' => 'The courgette is an herbaceous plant of the Cucurbitaceae family, it is also the edible fruit of this plant.

Zucchini is a common fruit in summer, the zucchini flower is also used in cooking. The different varieties of zucchini are cultivars of the species Cucurbita pepo, and of the subspecies Cucurbita pepo subsp. pepo to which the real pumpkin also belongs.',
                'localisation' => '',
            ],
            [
                'title' => 'Onion',
                'category' => 'Vegetable',
                'image' => 'https://images.unsplash.com/photo-1587412679203-b5cf445eccb8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '3 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '3 / week',
                'planting_sprouting' => '1.5 month',
                'description' => 'L\'oignon ou ognon (Allium cepa), est une espèce de plantes herbacées bisannuelles de la famille des Amaryllidaceae, largement et depuis longtemps cultivée comme plante potagère pour ses bulbes de saveur et d\'odeur fortes ou pour ses feuilles. Le terme désigne aussi le bulbe de cette plante récolté comme légume. Par extension, il désigne parfois familièrement en jardinage les bulbes d\'autres plantes, généralement non comestibles (par exemple : oignon de tulipe).',
                'localisation' => '',
            ],
            [
                'title' => 'Rose',
                'category' => 'Plant',
                'image' => 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '1 / week',
                'planting_sprouting' => '2 weeks',
                'description' => 'The rose is the flower of roses, shrubs of the genus Rosa and the family Rosaceae. The garden rose is characterized above all by the multiplication of its interlocking petals which gives it its characteristic shape.

Appreciated for its beauty and scent, it has been celebrated since ancient times by many poets and writers as well as painters for its colours and perfume. Its colours range from pure white to dark purple, yellow and all shades in between. It can be found in almost every garden and in many bouquets. She has become the "queen of flowers" in the Western world - the peony is competing for the title in China.',
                'localisation' => '',
            ],
            [
                'title' => 'Hydrangea',
                'category' => 'Plant',
                'image' => 'https://images.unsplash.com/photo-1501577316686-a5cbf6c1df7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=633&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '2.5 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '2.5 / week',
                'planting_sprouting' => '1 month',
                'description' => 'Hydrangea is a genus of shrubs and trees belonging to the family Hydrangeaceae of which the best known species is a hybrid species, called Hydrangea ×serratophylla, obtained by crossing Hydrangea macrophylla and Hydrangea serrata. Horticultural plants known as "Hydrangeas" can be distinguished from plants from nature by their inflorescences composed of almost all sterile flowers, which together form a ball or half ball.',
                'localisation' => '',
            ],
            [
                'title' => 'Lily',
                'category' => 'Plant',
                'image' => 'https://images.unsplash.com/photo-1501973931234-5ac2964cd94a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '1 / week',
                'planting_sprouting' => '1.5 month',
                'description' => 'Lilies are herbaceous plants of the family Liliaceae belonging to the genus Lilium.',
                'localisation' => '',
            ],
            [
                'title' => 'Tulips',
                'category' => 'Plant',
                'image' => 'https://images.unsplash.com/photo-1520031386004-475e4f187405?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '1.5 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '1.5 / week',
                'planting_sprouting' => '3 weeks',
                'description' => 'Tulips form a genus (Tulipa) of herbaceous plants in the Liliaceae family, which includes about 100 species native to the warm temperate regions of the Old World. Several species are widely cultivated as ornamental plants and have led to the creation of several thousand varieties.',
                'localisation' => '',
            ],
            [
                'title' => 'Mint',
                'category' => 'Aromatic',
                'image' => 'https://images.unsplash.com/photo-1582556135623-653b87486f21?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1295&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '5 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '5 / week',
                'planting_sprouting' => '1 month',
                'description' => 'Mints form a genus (Mentha) of herbaceous perennial plants of the family Lamiaceae (Labiatae), subfamily Nepetoideae, tribe Mint, subtribe Menthinae. This genus includes many species, many of which are cultivated as aromatic and condiment, ornamental or medicinal plants.',
                'localisation' => '',
            ],
            [
                'title' => 'Basil',
                'category' => 'Aromatic',
                'image' => 'https://images.unsplash.com/photo-1558070510-504a0db43997?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
                'sowed' => null,
                'planted' => null,
                'seedling_frequency' => '3.5 / week',
                'seedling_light' => 'Sunny',
                'planting_frequency' => '3.5 / week',
                'planting_sprouting' => '1.5 month',
                'description' => 'Basil or Roman Basil (Ocimum basilicum L.) is a species of herbaceous therophytic plants of the Lamiaceae family (labiaceae, labiaceae), cultivated as an aromatic and condiment plant. The plant is sometimes called Common Basil, Basil in Sauces, Royal Grass or Grand Basil. Common Basil is widely used in Italian cuisine, other varieties of basil are common in some Asian cuisines: Taiwan, Thailand, Vietnam, Cambodia and Laos.',
                'localisation' => '',
            ],
        ]);
    }
}
